---
name: Build Image and push

on: 
  push:
    branches:
      - prod

jobs:
  build-image:
    name: Build and Push
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build . -t blog-api
      - name: Push
        run: docker push vitals9367/blog-api:latest